server:
  port: 8081

api :
  userService:
    userOperations: localhost:8080/api/users/
    portfolioStatOperations: localhost:8080/api/statistic/
    currencyOperations: localhost:8080/api/currency/
    stockSearchOperations: localhost:8080/api/stocks/

telegram:
  bot-name: StocksBot
  api-key: 6126378813:AAE3K10-WLaKOz8pzG-Nkl5ibx0g6gUzf0k
  bot-owner: 908653889
