server:
  port: 8081

api :
  userService:
    userOperations: localhost:8080/api/users/
    portfolioStatOperations: localhost:8080/api/statistic/
    currencyOperations: localhost:8080/api/currency/
    stockSearchOperations: localhost:8080/api/stocks/

telegram:
  bot-name: ${botName}
  api-key: ${botToken}
  bot-owner: ${botOwner}
