server:
  port: 8080

api :
  stockConfig:
    stockService: stock-service:8002/api/stocks/
  currencyConfig:
    currencyService: cbr-service:8006/api/currency/
  openFigiConfig:
    openFigiService: openfigi-service:8007/api/stocks/
  stockInfoConfig:
    stockInfoService: stock-cache-service:8003/api/stocks/

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://postgres:5432/postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
