server:
  port: 8002

api :
  tinkoffConfig:
    tinkoffService: localhost:8004/api/stocks/
  moexConfig:
    moexService: localhost:8005/api/bonds/
  priceConfig:
    priceService: localhost:8003/api/prices/

springdoc:
  api-docs:
    path: /api-docs
