server:
  port: 8002

api :
  tinkoffConfig:
    tinkoffService: tinkoff-service:8004/api/stocks/
  moexConfig:
    moexService: moex-service:8005/api/bonds/
  priceConfig:
    priceService: stock-cache-service:8003/api/prices/

springdoc:
  api-docs:
    path: /api-docs
