server:
  port: 8003

logging:
  level:
    io.modicon.priceservice.application.client: debug

api :
  tinkoffConfig:
    tinkoffService: localhost:8004/api/stocks/

spring:
  redis:
    host: localhost
    port: 6379

springdoc:
  api-docs:
    path: /api-docs
