server:
  port: 8003

logging:
  level:
    io.modicon.stockcacheservice.application.client: debug

api :
  tinkoffConfig:
    tinkoffService: tinkoff-service:8004/api/stocks/

spring:
  redis:
    host: redis
    port: 6379

springdoc:
  api-docs:
    path: /api-docs
